development:
  adapter: postgresql
  encoding: unicode
  database: anyvine_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: anyvine_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: anyvine_production
  pool: 5
